version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout # special step to check out source code to working directory
      - run:
        name: test
        command: npm test 
      
